from db.dal.data_source.CollisionDataOttawaDAL import CollisionDataOttawaDAL
from db.dal.data_source.CollisionDataCalgaryDAL import CollisionDataCalgaryDAL
from db.dal.data_source.CollisionDataTorontoDAL import CollisionDataTorontoDAL
from db.dal.dimension_pre_stage.WeatherDimensionPreStageDAL import WeatherDimensionPreStageDAL