# CALGARY_STATIONS = (
#   'CALGARY INT\'L A',
#   'CALGARY INT\'L CS',
#   'CALGARY INTL A',
#   'COP UPPER'
# )

OTTAWA_STATIONS = (
    'OTTAWA CDA RCS',
    'OTTAWA MACDONALD-CARTIER INT\'L A',
    'OTTAWA INTL A'
)

TORONTO_STATIONS = (
    'PA MATTAMY ATHLETIC CENTRE',
    'TORONTO CITY',
    'TORONTO CITY CENTRE',
    'PA ROYAL CANADIAN YACHT CLUB',
    'PA DUFFERIN AND ST. CLAIR CIBC',
    'PA TORONTO HYUNDAI',
    'PA SCARBOROUGH TORONTO HUNT',
    'PA TORONTO NORTH YORK MOTORS',
    'PA ATMOS NORTH YORK',
    'PA DOWNSVIEW PARK',
    'PA DOWNSVIEW',
    'PA YORK UNIVERSITY',
    'PA MARKHAM NORTH TOYOTA',
    'TORONTO INTL A',
    'TORONTO LESTER B. PEARSON INT\'L A',
    'PA U OF T SCARBOROUGH TENNIS CENTRE',
    'PA HERSHEY CENTRE',
    'PA CONCORD RYDER',
    'TORONTO BUTTONVILLE A',
    'PA MONOPOLY PROPERTY MANAGEMENT',
    'PA ATMOS MISSISSAUGA'
)

WEATHER_STATIONS = OTTAWA_STATIONS + TORONTO_STATIONS
